Features/31 user referral
We-Are-Swissborg/WASB-Back pull request #33
Opened 2024-07-18 10:10 UTC by KeotiseuF

2024-07-18 18:39 UTC, Valdior requested changes
Ton lien entre les entités n'est pas propre. 
Tu pars sur le principe d'un string pour les users fileul. Ce qui n'est pas correct. Il faut penser 'objet's, 'entité'.

De plus cela ne correspond pas à ce qu'on s'était dis, à savoir garder l'ID du user dans les tables .

Cela donnerait un résultat suivant : 

1) Parrain userID->42
Voici mon code de parrainage ABCDE12

Tu stocke bien cette valeur dans le champ  referralId
Mais ce n'est pas au parrain de connaitre c'est fileules.

1 -> N

2) Le filleule userID -> 86

Mon parrain m'a donnée ce code pour m'inscrire ABCDE12

Il faut regarder à qui appartient ce code -> Au userId 42
J'enregistre cette donné chez le fileule car il ne peut avoir qu'un seul parrain.

3) Un autre fileule userID -> 495

Idem

Via le lien entre les entités, je peux savoir que le userId 42 à 2 fileules
select count (*) WHERE userReferred = 42
Je peux savoir qui est le parrain de mon user 495
select pseudo WHERE userId= (select userReferred where userid = 495)

Si ce n'est pas claire, on prévient moi, on se refait un call ;)

2024-07-18 18:39 UTC, Valdior commented on src/services/user.services.ts
Globalement bon, toutefois j'aimerai un peu que tu documentes ton code :) 
Egalement si possible d'ajouter des tests pour éviter des régressions :D

2024-07-19 02:58 UTC, KeotiseuF commented on src/services/user.services.ts
C'est noté, je ferai attention aux commentaires ;)

Et pour les tests, je les ai faits de la même façon que tu as intégré les tests pour le mot de passe. Ce qui fait que si tu veux qu'ils fonctionnent à l'initialisation, il faut appeler la logique dans le fichier dédié (init-db). Par contre, si tu parles des tests unitaires, je pensais que tu avais un souci avec JEST. Je t'ai même dit que je verrais ça, mais après tu étais d'accord :/

2024-07-20 09:06 UTC, Valdior commented
Dans la PR, tu ne réponds toujours pas à la demande initial.

Il ne faut pas garder le referral du user parrain, mais sont ID.
Il faut donc mettre une relation forte entre les entités et non pas un string

2024-07-20 10:04 UTC, KeotiseuF commented
> Dans la PR, tu ne réponds toujours pas à la demande initial.
> 
> Il ne faut pas garder le referral du user parrain, mais sont ID. Il faut donc mettre une relation forte entre les entités et non pas un string

Ah oui, c'est vrai. Je m'en occupe

2024-07-21 08:22 UTC, KeotiseuF commented on src/models/user.model.ts
Ta oublier 2 'register' à enlevé, pour les propriétés confidentiality et beContacted

2024-07-21 08:34 UTC, Valdior commented on src/models/user.model.ts
Bien vu le 'groups register' dans le User, il n'est en effet plus utile maintenant que nous avons un type spécifique

2024-07-21 10:29 UTC, Valdior approved these changes

2024-07-21 10:30 UTC, merged