add route for get all posts and one post
We-Are-Swissborg/WASB-Back pull request #58
Opened 2024-08-14 12:50 UTC by KeotiseuF

1. Ajout des routes pour la preview, création d'un post, récupération des posts.
2. Nettoie le texte qui se trouvait dans l'éditeur.
3. Ajout model pour les posts.
4.  Vérification qu'un fichier soit une image

Il manque la validation des autres admin ou modo, une variable dans le model pour indiquer la validation du post par les autres,
la route de suppression/update, Nodemailer et API for communiqué sur Discord pour prévenir d'un nouveau post ou refus

NOT MERGE FOR THE MOMENT

2024-08-14 21:47 UTC, KeotiseuF commented on src/models/post.model.ts
> +    declare content: string;
Pour quel raison sachant que ça évite les doublons ?

2024-08-15 08:20 UTC, Valdior commented on src/models/post.model.ts
> +    declare content: string;
Parce que ca alourdi les requetes DB pour rien. Dans un texte une lettre change et ce n'est plus unique. a quoi ca sert ?

2024-08-15 12:38 UTC, KeotiseuF commented on src/models/post.model.ts
> +    declare content: string;
Je ne savais pas que ça avait autant d'impact sur les requêtes, c'est noté je l'enlève. Je suis au courant mais le risque 0 n'existe pas dans cette situation.

2024-08-21 14:43 UTC, KeotiseuF commented
Optimisation de la page blog

1. Crée une route pour récupérer une rangé et non tous les posts.
2. Transforme les images des posts en WEBP et les redimensionnes.

Il manque la validation des autres admin ou modo, une variable dans le model pour indiquer la validation du post par les autres,
la route de suppression/update, Nodemailer et API for communiqué sur Discord pour prévenir d'un nouveau post ou refus

NOT MERGE FOR THE MOMENT

2024-08-25 19:24 UTC, Valdior requested changes
Discuter part discord

2024-09-01 08:29 UTC, Valdior approved these changes

2024-09-01 12:24 UTC, KeotiseuF commented
Il manque la validation des autres admin ou modo, une variable dans le model pour indiquer la validation du post par les autres,
Nodemailer et API for communiqué sur Discord pour prévenir d'un nouveau post ou refus

Je merge, je ferai une novelle PR pour les tâches qu'ils manquent comme convenu.

2024-09-01 18:26 UTC, Valdior commented
Il n'a jamais été question de validation d'autres admin ou modo jusqu'à maintenant, ni de communication avec Discord.
Ok pour le merge une fois que l'autre PR sera également valide

2024-09-03 07:14 UTC, merged